### ISSUE TITLE
how to edit in android studio 

### ISSUE THREAD

**Issue by youngrichu** [Swati4star/Travel-Mate#1]
Hi there 
 
i rly like this project: the idea, the features amazing. and i would love to to localize it and modify to my need but the problem is i'm kinda new to Android studio and i can't seems to be able to open and edit the files. so would you be so kind and give me some tips.

 thanks in advance :)

**Comment by Swati4star** [comment]
Hi @youngrichu 
Just follow the following steps
- Clone this repository.
- In Android Studio, Go to File -> New -> Import Project; and navigate to 'Android' subdirectory of this project
- Build the project, and install the missing dependencies
- Run it on your device or virtual device.

Feel free to ping if you face any error. :smile:

**Comment by youngrichu** [comment]
HI 

first i would like to thank you for your replay :smile: and  i just did exacly as you told me , but i run into some errors with the styles.xml file.
![android studio](https://cloud.githubusercontent.com/assets/3649930/20009156/798db59a-a2b4-11e6-96b9-d9276425cac2.PNG)

**Comment by Swati4star** [comment]
Well, you shouldn't get this error
I will recommend checking out the answers on this page.

http://stackoverflow.com/a/31980495
