### ISSUE TITLE
API Link Path 

### ISSUE THREAD

**Issue by sushilsaini04** [Swati4star/Travel-Mate#12]
i have upload API in http://abc.in website and give the following API Link into the Android Code 
public static  String apilink = "http://abc.in";
but this i not working. Request please correct where i am wrong

**Comment by Swati4star** [comment]
Try using 
public static String apilink = "http://abc.in/";

Also, I tried using 
http://abc.in/users/login.php?contact=1234567834&password=123456
but this shows 404:Not found

**Comment by Swati4star** [comment]
I guess you are done with this issue? 
I am closing this for now. If there is still some problem, you can reopen the issue.
