### ISSUE TITLE
Failed to load twitter feed

### ISSUE THREAD

**Issue by Niranjan-B** [Swati4star/Travel-Mate#16]
I was playing around with the code and found that the app crashes when "City Trends" is clicked. Here's the crash log ->
org.json.JSONException: End of input at character 0 of 
05-15 15:51:57.119 2857-2857/tie.hackathon.travelguide W/System.err:     at org.json.JSONTokener.syntaxError(JSONTokener.java:450)
05-15 15:51:57.119 2857-2857/tie.hackathon.travelguide W/System.err:     at org.json.JSONTokener.nextValue(JSONTokener.java:97)
05-15 15:51:57.119 2857-2857/tie.hackathon.travelguide W/System.err:     at org.json.JSONArray.<init>(JSONArray.java:92)
05-15 15:51:57.119 2857-2857/tie.hackathon.travelguide W/System.err:     at org.json.JSONArray.<init>(JSONArray.java:108)
05-15 15:51:57.119 2857-2857/tie.hackathon.travelguide W/System.err:     at tie.hackathon.travelguide.Tweets$1.-tie_hackathon_travelguide_Tweets$1_lambda$2(Tweets.java:110)
05-15 15:51:57.121 2857-2857/tie.hackathon.travelguide W/System.err:     at tie.hackathon.travelguide.Tweets$1$-void_onResponse_okhttp3_Call_call_okhttp3_Response_response_LambdaImpl0.run(Tweets.java)
05-15 15:51:57.121 2857-2857/tie.hackathon.travelguide W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
05-15 15:51:57.124 2857-2857/tie.hackathon.travelguide W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
05-15 15:51:57.125 2857-2857/tie.hackathon.travelguide W/System.err:     at android.os.Looper.loop(Looper.java:135)
05-15 15:51:57.127 2857-2857/tie.hackathon.travelguide W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5254)
05-15 15:51:57.127 2857-2857/tie.hackathon.travelguide W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
05-15 15:51:57.127 2857-2857/tie.hackathon.travelguide W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
05-15 15:51:57.127 2857-2857/tie.hackathon.travelguide W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
05-15 15:51:57.127 2857-2857/tie.hackathon.travelguide W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

The URL being called is -> "http://csinsit.org/prabhakar/tie/city/trends/twitter.php?city=2", which basically doesn't return any data, hence the JSON Exception.

**Comment by prabhakar267** [comment]
@Niranjan-B I have added the updated code for this bug in c9335a772ef0d843e32a80046c103bf6f56404cd.

Mention: @Swati4star
