### ISSUE TITLE
places-api.php don't work

### ISSUE THREAD

**Issue by marianofumante1** [Swati4star/Travel-Mate#18]
Hi, i have set the constants and connection file and all php file work fine, but the file places-api give me an error type 500. Could you help me?
Thanks in advance

**Comment by prabhakar267** [comment]
@marianofumante1 500 error can come due to a lot of reasons, it is an Internal Server Error. You can refer to http://php.net/manual/en/function.error-reporting.php for enabling full error reporting and then probably you can debug it.

**Comment by marianofumante1** [comment]
Hello dear,
But all other files work fine. Could be an error in request for places-api?
Thanks for help

**Comment by prabhakar267** [comment]
It works fine on my machine. If you could enable error reporting and then show me the screenshot of the error, I would be able to help you better.

**Comment by prabhakar267** [comment]
@marianofumante1  I have added the error reporting code
I am closing the issue, feel free to reopen it. If you face any problem. :+1:
