### ISSUE TITLE
something wrong with api or server

### ISSUE THREAD

**Issue by maklaymiklyxa** [Swati4star/Travel-Mate#19]
![image](https://cloud.githubusercontent.com/assets/28544059/26227953/67bc280a-3c3e-11e7-91ab-00dbb7f31613.png)
if you open something it's loading all time and cant get some information about сity or places on map or temperature.
P.S. sorry for my english.

**Comment by prabhakar267** [comment]
@maklaymiklyxa you would need to setup a server of your own
We (me and @Swati4star ) are in process of creating a public server for the same, till the time you would have to manage with a personal server.

**Comment by Swati4star** [comment]
Thank you for pointing it out. 
Fixed by https://github.com/Swati4star/Travel-Mate/commit/3210daac328c01a22aa28e7ec7c4b890c2636cb0
