### ISSUE TITLE
Android: jack is deprecated

### ISSUE THREAD

**Issue by AnandPilania** [Swati4star/Travel-Mate#24]
[jack is deprecated](https://github.com/JakeWharton/butterknife/issues/990#issuecomment-310932440)

**Comment by Swati4star** [comment]
@gugakatsi Should we revert back the jack changes?
A lot of people are even having the problem in setting up the project

**Comment by gugakatsi** [comment]
@Swati4star , i guess we should stay with jack for a while , unless preview of android studio becomes stable , not gonna take long i guess , let me know your opinion about that.

**Comment by Swati4star** [comment]
I think we should move. People really are having setup issues.
And also jack is no longer maintained. We will eventually end up with some other issue if we don't shift now.

**Comment by gugakatsi** [comment]
@Swati4star yeah , i guess u're right , and still who knows when google gonna publish stable version of AS , if @AnandPilania wants to work on that issue would be good or i'd happy too , just let me know.

**Comment by Swati4star** [comment]
@gugakatsi I guess before refactoring, we should work on this?
Are you ready to take up this issue?
It would be better to refactor after this.

**Comment by gugakatsi** [comment]
@Swati4star yeap i  have some time tomorrow evening so i can fix it , so i'll rollback jack changes.

**Comment by gugakatsi** [comment]
@Swati4star just to mention i am currenty working on it , will push in few minutes.

**Comment by Swati4star** [comment]
Fixed by https://github.com/Swati4star/Travel-Mate/pull/38

Thanks @gugakatsi 👍
