### ISSUE TITLE
Add java checkstyle 

### ISSUE THREAD

**Issue by prabhakar267** [Swati4star/Travel-Mate#28]
Ref: https://github.com/checkstyle/checkstyle

Integrate checkstyle to make the java code uniform

**Comment by codeteo** [comment]
Please check PR #37 which integrates `checkstyle` to the project :+1:

**Comment by Swati4star** [comment]
Fixed by https://github.com/Swati4star/Travel-Mate/pull/37
Thanks @codeteo 👍
