### ISSUE TITLE
Change error responses for City Hotels API

### ISSUE THREAD

**Issue by prabhakar267** [Swati4star/Travel-Mate#3]
Change the responses for the [```get-city-hotels.php```](https://github.com/Swati4star/Travel-Mate/blob/master/APIs/get-city-hotels.php).
If the response from Here API is empty or if the city ID is incorrect, send the responses accordingly 

Note : Take reference from [```bus-booking.php```](https://github.com/Swati4star/Travel-Mate/blob/master/APIs/bus-booking.php)

**Comment by tictakk** [comment]
Hey @prabhakar267 , I would like to work on this. Quick question. In the bus-booking.php, after you get the query results. It looks like you're building a temp_array with default values. What is that used for? Is something like that necessary for get-city-hotels.php? Thanks

**Comment by prabhakar267** [comment]
@tictakk Sorry for replying so late
No it is not necessary in ```get-city-hotels.php``` so you can skip that part

**Comment by jazzmann30** [comment]
Hi @prabhakar267 , first time trying to contribute here. Is this issue been assigned to somebody already?  Also a quick question, will the closed issue #5 have an impact on this issue?

**Comment by prabhakar267** [comment]
@jazzmann30 
@tictakk  is working on this issue, you can probably take up some other issue :+1:

**Comment by MJBrennan** [comment]
Hi has this issue been resolved yet?

**Comment by prabhakar267** [comment]
@MJBrennan No!

**Comment by jazzmann30** [comment]
I thought I was to look for another issue since somebody is trying to
resolve this.

**Comment by iamhofo** [comment]
I'd like to do this
