### ISSUE TITLE
Give more verbose error if connections file is missing

### ISSUE THREAD

**Issue by prabhakar267** [Swati4star/Travel-Mate#31]
If the user has not generated connection.inc.php file, he should get a more verbose error asking him to add the file.

**Comment by suksit** [comment]
Could you elaborate more on this? How should the error message be shown? e.g. as JSON or just simple text. Should we also send the status code (maybe 500)?, etc.

**Comment by prabhakar267** [comment]
I think an appropriate JSON response and an 500 response code would be good enough!

**Comment by haridev22** [comment]
@prabhakar267 : I am a first timer and I would like to take this up if no one is working on this.

**Comment by prabhakar267** [comment]
Closing since already taken up in v2.
