### ISSUE TITLE
Butterknife and more

### ISSUE THREAD

**Issue by gugakatsi** [Swati4star/Travel-Mate#6]
is there any reason , there is no use of butterknife? thanks in advance.

**Comment by Swati4star** [comment]
Hi. Thanks for the advice.
Actually I wasn't acquainted with using butterknife when I started working on the project.

**Comment by Swati4star** [comment]
If anyone is interested in working on this issue, feel free to comment.

**Comment by gugakatsi** [comment]
i will , thanks.

**Comment by gugakatsi** [comment]
@Swati4star  i have a question , for example you have many setOnClickListener calls there , so would't it be good to implement onClickListener, i guess in this situation would be better.

**Comment by Swati4star** [comment]
Yeah. Nice idea. It would be better. Please do the changes.

**Comment by gugakatsi** [comment]
@Swati4star somehow i can't push it , tells me that some file is too large..

**Comment by Swati4star** [comment]
Can you please post a screenshot, or paste the error message over here?

**Comment by gugakatsi** [comment]
ofc, no problem ,I'll do it tomorrow morning.

**Comment by gugakatsi** [comment]
@Swati4star here you go : 
<pre>
Counting objects: 59, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (54/54), done.
Writing objects: 100% (59/59), 267.11 MiB | 32.00 KiB/s, done.
Total 59 (delta 40), reused 5 (delta 0)
remote: Resolving deltas: 100% (40/40), completed with 38 local objects.
remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
remote: error: Trace: b68df5dfea82f9dc7d1a6fc17c274639
remote: error: See http://git.io/iEPt8g for more information.
remote: error: File Android/java_pid10771.hprof is 1317.12 MB; this exceeds GitHub's file size limit of 100.00 MB
To https://github.com/gugakatsi/Travel-Mate
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://github.com/gugakatsi/Travel-Mate'
</pre>

**Comment by Swati4star** [comment]
The hprof file is a dump file. Just delete this file, and then try pushing it

**Comment by gugakatsi** [comment]
@Swati4star pushed it , thanks :+1:
